server:
  port: 8082

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/animal_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: lms*!$Ms0828
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지
    jdbc:
      initialize-schema: always  # 배치 메타데이터 테이블 자동 생성

app:
  jwtExpirationInMs: 86400000 # 24시간

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.animalhosreviewadmin.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.animalhosreviewadmin: DEBUG