server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/animal_hospital?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: lms*!$Ms0828
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwtExpirationInMs: 86400000 # 24시간

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.animalhosreviewadmin.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.animalhosreviewadmin: DEBUG